apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0ftu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0ftu
    app.kubernetes.io/part-of: ci10t-786-0064-app
  name: devfile-sample-0ftu
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-0ftu
status:
  loadBalancer: {}
